# Generated by Django 5.2.5 on 2025-08-25 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العادة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], default='daily', max_length=20, verbose_name='التكرار')),
                ('goal', models.IntegerField(blank=True, null=True, verbose_name='الهدف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عادة',
                'verbose_name_plural': 'العادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('completed', models.BooleanField(default=False, verbose_name='مكتملة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='habits.habit')),
            ],
            options={
                'verbose_name': 'تتبع العادة',
                'verbose_name_plural': 'تتبع العادات',
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
